### ISSUE TITLE
Z2M 1-19-1 upgrade error : panId collision detected (expected=6754, actual=6756)

### ISSUE THREAD

**Issue by tirasol** [tabspacekr/TabSpaceOS#5]
z2m repository변경 및 업그레이드 후, 에러발생
<pre>
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] socat.sh: executing... 
[11:34:32] INFO: Socat not enabled, marking service as down
[cont-init.d] socat.sh: exited 0.
[cont-init.d] zigbee2mqtt.sh: executing... 
[11:34:35] INFO: MQTT available, fetching server detail ...
[11:34:36] INFO: MQTT server settings not configured, trying to auto-discovering ...
[11:34:38] INFO: Configuring 'mqtt://core-mosquitto:1883' mqtt server
[11:34:39] INFO: Previous config file found, checking backup
[11:34:39] INFO: Creating backup config in '/config/zigbee2mqtt/.configuration.yaml.bk'
[11:34:39] INFO: Adjusting Zigbee2mqtt core yaml config with add-on quirks ...
[cont-init.d] zigbee2mqtt.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:34:43] INFO: Handing over control to Zigbee2mqtt Core ...
> zigbee2mqtt@1.19.1 start /app
> node index.js
Zigbee2MQTT:error 2021-06-07 11:35:18: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2021-06-07 11:35:18: Failed to start zigbee
Zigbee2MQTT:error 2021-06-07 11:35:18: Check https://www.zigbee2mqtt.io/information/FAQ.html#help-zigbee2mqtt-fails-to-start for possible solutions
Zigbee2MQTT:error 2021-06-07 11:35:18: Exiting...
Zigbee2MQTT:error 2021-06-07 11:35:18: Error: network commissioning failed - panId collision detected (expected=6754, actual=6756)
    at ZnpAdapterManager.<anonymous> (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/manager.js:337:23)
    at Generator.next (<anonymous>)
    at fulfilled (/app/node_modules/zigbee-herdsman/dist/adapter/z-stack/adapter/manager.js:24:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zigbee2mqtt@1.19.1 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zigbee2mqtt@1.19.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-06-07T02_35_18_512Z-debug.log
[11:35:19] INFO: Handing over control to Zigbee2mqtt Core ...
</pre>

**Comment by tirasol** [comment]
z2m의 configuration의 advanced 항목의 pan_id를 6754에서 6756으로 변경하여 해결 가능

<pre>
advanced:
  log_level: warn
  pan_id: 6756
</pre>
